version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping depolyment package..."
      - zip -r deployment_package1.zip image_search.py
      - zip -r deployment_package2.zip image-index.py
  post_build:
    commands:
      - echo "Updating lambda functions..."
      - aws lambda update-function-code --function-name image_search --zip-file fileb://deployment_package1.zip
      - aws lambda update-function-code --function-name image-index --zip-file fileb://deployment_package2.zip
      - echo "Done"
      
version: 0.2

phases:
  build:
    commands:
      - echo "Building the Lambda functions..."
      - pwd
      - cd index-photos
      - pwd
      - ls
      - zip -r ../index-photos.zip *
      - cd ../image_search
      - pwd
      - ls
      - zip -r ../image_search.zip *
      - cd ..
      - ls
      - pwd

  post_build:
    commands:
      - pwd
      - ls
      - echo "Updating the Lambda functions..."
      - aws lambda update-function-code --function-name index-photos --zip-file "fileb://index-photos.zip"
      - aws lambda update-function-code --function-name image_search --zip-file "fileb://image_search.zip"
